menu:
    Blog: /
    Archive: /archives/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-125563706-1

# Copyright Infomation
startyear: 2015
